### PR TITLE
Dont run everywhere

### PR DESCRIPTION
**Pull request by ccamacho**

### CODE REVIEW

**Review by philroche — APPROVED** [review]
This all looks good. 

Not too familiar with github action workflows but based on 
 https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context  and https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif I am +1

**Comment by jistr** [comment]
Looks good but both need changed commit messages from "Chg" to "Dev", we don't want this kind of info bubbling up into changelog, which should be user-facing.

When selecting the commit message between Dev and the others (New/Chg/Fix/Oth), the question to ask is: "Does this commit change something about usage of OS Migrate in production scenarios?". If the answer is no, the commit always has to be "Dev".

**Comment by jistr** [comment]
Adding extra detail as we have @philroche onboarding: we have an example where we let a commit message slip recently in the unreleased changelog: https://os-migrate.github.io/os-migrate/changelog.html

"Lint tests are failing with the line lenght <=100. This commits increases the limit to 150."  -- not really something user wants to read when they are curious what changed in the new release since the last one :)

**Comment by jistr** [comment]
The changelog generation is explained in dev docs https://os-migrate.github.io/os-migrate/devel/contributing-general.html#commit-messages-for-changelog

**Review by jistr — APPROVED** [review]

**Pull request merged**
