### PR TITLE
Cap openstacksdk below 0.99

### PR DESCRIPTION
**Pull request by priteau**
Release 0.99.0 of openstacksdk brings major breaking interface changes.

### CODE REVIEW

**Comment by jistr** [comment]
Ah yes we have this in CI [1] but we forgot to pin it in the docs too. Thanks!

[1] https://github.com/os-migrate/os-migrate/blob/ccb4d5c5ee822baa2c443b69c55a449ad0782b71/toolbox/build/venv-requirements-ansible-latest.txt

**Review by jistr — APPROVED** [review]

**Comment by priteau** [comment]
Can this be merged? It only changes documentation.

**Comment by priteau** [comment]
I updated the commit to use the `Dev` tag.

**Comment by jistr** [comment]
Thanks :)

**Comment by jistr** [comment]
We've now fixed CI in https://github.com/os-migrate/os-migrate/pull/592 but i think both of your PRs need to be rebased. If you'd want us to do it and you've allowed maintainer edits on the PRs, i could try doing the rebase.

**Comment by jistr** [comment]
Ah the lint on commit messages is case sensitive, so it has to be `dev` rather than `Dev`. I see it's incorrect in the developer docs, sorry about that, we'll fix it.

**Comment by jistr** [comment]
I updated the docs in #593.

**Comment by jistr** [comment]
There is something wrong with one of the tests (despite them passing today on another PR) but it doesn't make sense to keep bashing this little change that only affects documentation. I'll override the CI. Thanks for the patch and for your patience with the CI issues :).

**Pull request merged**
