### PR TITLE
Fix: clean up src+dst clouds after workload migration failure, Chg: configurable boot volume prefix

### PR DESCRIPTION
**Pull request by jistr**
I put these two commits into a single PR because they would conflict on merging otherwise.

### CODE REVIEW

**Comment by jistr** [comment]
Gah this needs a fix for the docs build job re podman, rebasing...

**Comment by jistr** [comment]
I will add destination cloud cleanup here too, almost done.

**Comment by jistr** [comment]
Here's how the workload log looked when i inserted an artificial failure between the volume transfer and creation of the destination instance, it seems to do the right thing:

```
2021-02-17 10:59:48,960:INFO: Stopping exports from source conversion host... (import_workload_src_cleanup:314)
2021-02-17 10:59:56,788:DEBUG: Stopping NBD export PIDs (['80826', '81059']) (import_workload_src_cleanup:319)
2021-02-17 11:00:02,722:INFO: Waiting for lock /var/lock/v2v-migration-lock... (workload_common:36)
2021-02-17 11:00:22,894:INFO: Currently used ports: [49152, 49153] (workload_common:239)
2021-02-17 11:00:22,894:INFO: Cleaning used ports: set() (workload_common:303)
2021-02-17 11:00:38,155:DEBUG: Released lock:  (workload_common:60)
2021-02-17 11:00:38,156:INFO: Waiting for lock /var/lock/v2v-source-volume-lock... (workload_common:36)
2021-02-17 11:00:43,476:INFO: Detaching volumes from the source conversion host. (import_workload_src_cleanup:339)
2021-02-17 11:00:45,937:INFO: Inspecting volume 47f69b10-bac8-4533-aee2-2d0562d1e844 (import_workload_src_cleanup:343)
2021-02-17 11:00:56,277:INFO: Inspecting volume 968f128a-6ba9-4c71-b1c8-6db3e8669869 (import_workload_src_cleanup:343)
2021-02-17 11:01:12,455:DEBUG: Released lock:  (workload_common:60)
2021-02-17 11:01:12,456:INFO: Re-attaching volumes to source VM... (import_workload_src_cleanup:362)
2021-02-17 11:01:12,457:INFO: Removing copy of root volume (import_workload_src_cleanup:366)
2021-02-17 11:01:18,668:INFO: Deleting temporary root device image (import_workload_src_cleanup:379)
2021-02-17 11:01:23,688:INFO: Attaching 47f69b10-bac8-4533-aee2-2d0562d1e844 back to source VM (import_workload_src_cleanup:390)
2021-02-17 11:01:53,700:INFO: Waiting for lock /var/lock/v2v-destination-volume-lock... (workload_common:36)
2021-02-17 11:02:00,913:INFO: Detaching volumes from the destination conversion host. (import_workload_dst_failure_cleanup:185)
2021-02-17 11:02:02,530:INFO: Volume afa5487e-00d7-4a55-a18f-c309c3a878ba is not attached to conversion host, skipping detach. (import_workload_dst_failure_cleanup:193)
2021-02-17 11:02:03,042:INFO: Volume 83905bd0-ac72-4268-8364-1ec6616ef865 is not attached to conversion host, skipping detach. (import_workload_dst_failure_cleanup:193)
2021-02-17 11:02:12,691:DEBUG: Released lock:  (workload_common:60)
2021-02-17 11:02:12,692:INFO: Deleting migrated volumes from destination. (import_workload_dst_failure_cleanup:211)
2021-02-17 11:02:14,680:INFO: Deleting volume afa5487e-00d7-4a55-a18f-c309c3a878ba. (import_workload_dst_failure_cleanup:221)
2021-02-17 11:02:21,269:INFO: Deleting volume 83905bd0-ac72-4268-8364-1ec6616ef865. (import_workload_dst_failure_cleanup:221)
```

**Review by ccamacho — APPROVED** [review]
Docs are rendered correctly and passed the CI, we discussed the change in the volume prefix in the squad call, we should have this in 0.7.0

**Comment by jistr** [comment]
Thanks! I'll merge and start preparing 0.7.

**Pull request merged**
