### PR TITLE
Dev: Update README to point functional tests badge to the periodic job

### PR DESCRIPTION
**Pull request by philroche**
This commit updates the README to have the functional test badge to point
to the periodic result instead of the test result from push events.

### CODE REVIEW

**Comment by ccamacho** [comment]
This is AwEsOmE!!!!!!

Thanks for your first contribution!!

**Comment by ccamacho** [comment]
The e2e job shouldn't be affected by this PR but it's a nice way to exercise the way we trigger the e2e jobs.

**Review by ccamacho — APPROVED** [review]
LGTM :)

**Comment by jistr** [comment]
Cool, thanks :)

**Review by jistr — APPROVED** [review]

**Pull request merged**
