### PR TITLE
Include network mappings in wrapper input.

### PR DESCRIPTION
**Pull request by mrnold**

### CODE REVIEW

**Comment by ccamacho** [comment]
Im testing this in the e2e job and it works as expected.

**Comment by jistr** [comment]
Looks good, @mrnold should we mark the PR as ready for review? (It's a draft PR now.)

**Comment by ccamacho** [comment]
@jistr yeahp @mrnold and I were speaking about his and this is making fail some manual tests @mrnold is running. I asked him to create the PR to not forget about it and I'm cherry-picking it for the e2e job.

**Comment by mrnold** [comment]
Sure, it would be okay to merge this. I can work around my manual test issue for now and send another pull request if I find the right way to fix it.

**Pull request merged**
